version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: biblebookministry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kingmaker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    container_name: biblebookministry_backend
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/biblebookministry
      DB_USERNAME: postgres
      DB_PASSWORD: kingmaker
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8085:8085"

volumes:
  postgres_data:
  redis_data:


