spring.application.name=bibleandbookministry

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.baseline-on-migrate=true


server.port=8085

# Hibernate Properties
spring.jpa.properties.hibernate.statement_cache.size=0
spring.jpa.properties.hibernate.prepare_sql=false


logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# HikariCP Connection Pooling
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=0
spring.datasource.hikari.data-source-properties..prepStmtCacheSqlLimit=0


# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration


logging.level.org.eclipse.angus.mail=WARN
logging.level.org.nobleson = debug
logging.level.jdbc.sqlonly=DEBUG
logging.pattern.console= ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=15552000000L

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.file-size-threshold=200MB

spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=5m

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

debug=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

sentry.dsn=https://c9550a771633e2db112bca0127930429@o4509280831078400.ingest.de.sentry.io/4509709437501520
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true

